services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql-container2
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD : "true"
      MYSQL_DATABASE: drugstore
    ports:
      - "3309:3306"
    networks:
      - mynetwork
    volumes:
      - mysql_data:/var/lib/mysql
  app:
    image: drugstore:latest
    container_name: drugstore-container
    depends_on:
      - mysql
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container2:3306/drugstore?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
    networks:
      - mynetwork
networks:
  mynetwork:
    name: hospital_mynetwork
    driver: bridge

volumes:
  mysql_data:
